In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import OneHotEncoder

C:\Users\zmz22\Anaconda3\lib\site-packages\ipykernel\parentpoller.py:116: UserWarning: Parent poll failed.  If the frontend dies,
                the kernel may be left running.  Please let us know
                about your system (bitness, Python, etc.) at
                ipython-dev@scipy.org
  ipython-dev@scipy.org""")

In [2]:
# input data/change column name/merge data
people_data=pd.read_csv('people.csv',parse_dates=['date'])
test_act_data=pd.read_csv('act_test.csv',parse_dates=['date'])
train_act_data=pd.read_csv('act_train.csv',parse_dates=['date'])

In [7]:
def data_treatment(name):
    dataset=name
    for i in list(dataset.columns):
        if i not in ['people_id','activity_id','date','char_38','outcome']:
            if dataset[i].dtype=='object':
                dataset[i].fillna('type 0',inplace=True)
                dataset[i] = dataset[i].apply(lambda x: x.split(' ')[1])
                dataset[i]=pd.to_numeric(dataset[i].astype(np.int32))
            elif dataset[i].dtype=='bool':
                dataset[i]=dataset[i].astype(np.int8)
    dataset['people_id']=dataset['people_id'].apply(lambda x:x.split('_')[1])
    dataset['people_id']=pd.to_numeric(dataset['people_id']).astype(int)
    return dataset
# train_act_data=data_treatment(train_act_data)

In [8]:
train_act_data=train_act_data.drop('char_10',axis=1)
test_act_data=test_act_data.drop('char_10',axis=1)

In [9]:
train_act_data=data_treatment(train_act_data)   
test_act_data=data_treatment(test_act_data)   
people_data=data_treatment(people_data)

In [10]:
column_people=np.arange(1,41)
a=people_data.columns[column_people]
b=['pp_'+people_data.columns[i] for i in column_people]
mapping_people=dict(zip(a,b))

column_train=[2,*np.arange(4,14)]
a_1=train_act_data.columns[column_train]
b_1=['act_'+train_act_data.columns[i] for i in column_train]
mapping_train=dict(zip(a_1,b_1))

column_test=[2,*np.arange(4,13)]
a_2=test_act_data.columns[column_test]
b_2=['act_'+test_act_data.columns[i] for i in column_test]
mapping_test=dict(zip(a_2,b_2))
 
people_data=people_data.rename(columns=mapping_people)
test_act_data=test_act_data.rename(columns=mapping_test)
train_act_data=train_act_data.rename(columns=mapping_train)

In [12]:
# test_data=pd.merge(test_act_data,people_data,on='people_id')
train_data=train_act_data.merge(people_data,on='people_id',how='left', left_index=True)
test_data=test_act_data.merge(people_data,on='people_id',how='left', left_index=True)

In [13]:
train_data.head(50)

,people_id,activity_id,act_date,activity_category,act_char_1,act_char_2,act_char_3,act_char_4,act_char_5,act_char_6,...,pp_char_29,pp_char_30,pp_char_31,pp_char_32,pp_char_33,pp_char_34,pp_char_35,pp_char_36,pp_char_37,pp_char_38
0,100,act2_1734928,2023-08-26,4,0,0,0,0,0,0,...,0,1,1,0,0,1,1,1,0,36
0,100,act2_2434093,2022-09-27,2,0,0,0,0,0,0,...,0,1,1,0,0,1,1,1,0,36
0,100,act2_3404049,2022-09-27,2,0,0,0,0,0,0,...,0,1,1,0,0,1,1,1,0,36
0,100,act2_3651215,2023-08-04,2,0,0,0,0,0,0,...,0,1,1,0,0,1,1,1,0,36
0,100,act2_4109017,2023-08-26,2,0,0,0,0,0,0,...,0,1,1,0,0,1,1,1,0,36
0,100,act2_898576,2023-08-04,4,0,0,0,0,0,0,...,0,1,1,0,0,1,1,1,0,36
1,100002,act2_1233489,2022-11-23,2,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,0,76
1,100002,act2_1623405,2022-11-23,2,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,0,76
2,100003,act2_1111598,2023-02-07,2,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_1177453,2023-06-28,2,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_133509,2022-08-10,4,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_1408475,2023-03-02,4,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_1610829,2022-09-13,2,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_1688731,2023-02-10,4,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_1961720,2023-06-28,4,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_1988351,2022-08-23,2,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_2198176,2022-08-16,2,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_2437661,2023-02-02,2,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_2476911,2023-03-02,2,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_2557270,2022-08-30,4,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_2581989,2023-02-21,2,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_3116385,2023-02-15,2,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_3159712,2022-08-30,2,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_3292005,2023-05-03,2,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_3461867,2023-08-02,2,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_3468306,2023-03-02,4,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_3867292,2023-02-10,2,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_3990676,2023-08-30,4,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_4102292,2023-08-30,2,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_4160587,2023-02-21,2,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_4392666,2022-08-10,2,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_4438110,2022-08-25,2,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_4511875,2022-09-06,2,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_4568041,2022-08-10,2,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_4582681,2022-08-30,2,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_4665065,2022-08-26,2,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_4808411,2022-08-10,4,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_666224,2023-02-02,4,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_6962,2023-06-28,4,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_787846,2023-07-27,2,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_79633,2023-05-03,4,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
2,100003,act2_992474,2023-08-30,2,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,99
4,100006,act2_2358115,2022-10-05,4,0,0,0,0,0,0,...,0,0,1,0,0,0,1,1,0,84
4,100006,act2_2380649,2022-07-27,3,0,0,0,0,0,0,...,0,0,1,0,0,0,1,1,0,84
4,100006,act2_632935,2022-10-05,4,0,0,0,0,0,0,...,0,0,1,0,0,0,1,1,0,84
7,100013,act2_1667803,2023-01-26,5,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,91
7,100013,act2_2229,2023-01-25,5,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,91
7,100013,act2_225752,2023-01-26,5,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,91
7,100013,act2_2601949,2023-01-25,5,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,91
7,100013,act2_3059098,2023-01-25,5,0,0,0,0,0,0,...,0,0,1,1,1,1,0,1,1,91

In [14]:
train_data.columns.to_series().groupby(train_data.dtypes).groups

{dtype('int32'): Index(['people_id', 'activity_category', 'act_char_1', 'act_char_2',
        'act_char_3', 'act_char_4', 'act_char_5', 'act_char_6', 'act_char_7',
        'act_char_8', 'act_char_9', 'pp_char_1', 'pp_group_1', 'pp_char_2',
        'pp_char_3', 'pp_char_4', 'pp_char_5', 'pp_char_6', 'pp_char_7',
        'pp_char_8', 'pp_char_9'],
       dtype='object'),
 dtype('<M8[ns]'): Index(['act_date', 'pp_date'], dtype='object'),
 dtype('int8'): Index(['pp_char_10', 'pp_char_11', 'pp_char_12', 'pp_char_13', 'pp_char_14',
        'pp_char_15', 'pp_char_16', 'pp_char_17', 'pp_char_18', 'pp_char_19',
        'pp_char_20', 'pp_char_21', 'pp_char_22', 'pp_char_23', 'pp_char_24',
        'pp_char_25', 'pp_char_26', 'pp_char_27', 'pp_char_28', 'pp_char_29',
        'pp_char_30', 'pp_char_31', 'pp_char_32', 'pp_char_33', 'pp_char_34',
        'pp_char_35', 'pp_char_36', 'pp_char_37'],
       dtype='object'),
 dtype('int64'): Index(['act_outcome', 'pp_char_38'], dtype='object'),
 dtype('O'): Index(['activity_id'], dtype='object')}